name: Laura Gomez Navarro, Postdoc
markdown: kramdown
permalink: /blog/2019/03/19/site-launch

# Site Author
author:
  name             : "Laura"
  avatar           : "profile.png"
  bio              : "Your biography for the left-hand sidebar"
  location         : "Location"
  employer         :
  googlescholar    : "http://yourfullgooglescholarurl.com"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  linkedin         :
  orcid            : "http://orcid.org/yourorcidurl"
  twitter          : "replacethistwitterhandle"

header:
  image: https://linkedinheaders.com/uncategorized/ocean-waves/
